### ISSUE TITLE
Refactor modeltype `sediment`

### ISSUE THREAD

**Issue by verseve** [Deltares/Wflow.jl#382]
### Feature type

Refactor the sediment model, i.e., re-organize the model's code without adding new or removing existing features.

### Improvement Description

The initialization of the sediment model takes place in one function (`initialize_sediment_model`) of over 140 lines of code.
This is poorly maintainable and should be split up into smaller individual logical steps.
In addition, the parameters used for initializing the sediment model are, currently, stored alongside the parameters of all other models / concepts in wflow.
Sediment model parameters should be extracted into its own parameter `Struct`.
The extraction of the sediment model parameters should include the re-coupling of sediment model parameter to other models that require access to sediment model parameters.

see also main issue https://github.com/Deltares/Wflow.jl/issues/351

### Tasks

- [ ] #425 
- [ ] #451  
- [ ] #453  
- [ ] Store sediment model parameters in a separate `Struct`
- [ ] Refactor the sediment model to use its own parameter `Struct` instead of the `Model` struct
- [ ] Remove sediment model parameters from the `Model` struct
- [ ] Fix all sediment model parameter access invalidations

**Comment by hboisgon** [comment]
Looking through the Model, I see the following possibilities for new ``Struct``.

The main points (still to decide) are:

- Move some of the parameter calculations to HydroMT: 
     - soil mean sediment diameter d50
     - Govers parameters: nGovers, cGovers 
     - soil fractions of clay/silt/sand/small and large aggregates
     - Kodatie parameter
     - Bed and bank erodibility based on critical shear stress: kdbed, kdbank
- Combine river and overland transport capacities in the same structs (they all depend on flow velocity be it shallow overland flow or more concentrated river flow)
- Create a separate ``Struct`` for waterbodies (no real distinction here between lake and reservoir)? Can the one for SBM be re-used?
- Create a SedimentParticle ``Struct`` containing at least the sediment properties for each class. Should this class also contains the different variables and states of the model (ie soil erosion, soil particles entering the river, river erosion, river deposition, sediment flux in suspended/bed load etc...)?
- Organisation of the RiverSediment struct


## Sediment model: potential new structs

### SoilErosion
Existing model can compute total erosion or sum of erosion for different sources (overland flow, rainfall, wind etc.). I guess we then need a main SoilErosion struct that could switch between summing erosion from different sources.
So far in wflow, we support erosion from overland flow (1 concept) and from rainfall (2 concepts).
The flexible struct could allow for example then if only soil erosion is of interest to allow wflow to compute it from the most famous equations like USLE or RUSLE.

**General**

- Parameters: n, yl, xl, riverfrac, wbcover(resareas, lakeareas), dl, dw, rivcell, timestep
- Variables: soilloss, erosclay (etc), sedspl etc, sedov etc
- Boundary conditions: precipitation, h_land, q_land

**Interception** 
Note: re-use SBM – right now only used with EUROSEM concept

- Concept: Rutter / Gash
     - Parameters: sl, swood, kext, cmax, canopygapfraction, leaf_area_index
     - Variables: interception, canopygapfraction? (check in sbm)
     - Boundary conditions: precipitation

**Rainfall erosion** 
Note: can be computed for each particle class separately

- Concept: EUROSEM
     - Parameters: erosk, erosspl, pathfrac, soil_fraction, canopyheight, canopygapfraction
     - Variables: sedspl
     - Boundary conditions: precipitation, interception
 - Concept: ANSWERS
     - Parameters: usleC, usleK, pathfrac, soil_fraction
     - Variables: sedspl
     - Boundary conditions: precipitation

**Overland flow erosion** 
Note: can be computed for each particle class separately

- Concept: ANSWERS
     - Parameters: erosov, usleC, usleK, slope, pathfrac, slope, soil_fraction
     - Variables: sedov 
     - Boundary conditions: velocity_land(h_land, q_land)

### OverlandFlowSediment
So far we have one equation for transport which depends on transport capacity (3 concepts). Transport capacity can either be computed for a total sediment load (2 concepts) or with particle differentiation (1 concept, necessary if river transport should be calculated later).
River/reservoir/lake cells start to appear here to make sure overland flow sediment transport stops in river cells or at the waterbody outlet.

**General**

- Parameters: timestep, dw, n, rivcell
- Variables: transport_capacity, sediment_flow (olsed etc), sediment reaching the river (inlandsed etc)
- Boundary conditions: erosclay etc

**TransportCapacity**

- Concept: Govers – only for total sediment
     - Parameters: timestep, dw, slope, cGovers, nGovers, sediment density
     - Variables: transport_capacity
     - Boundary conditions: velocity (q_land, h_land)

- Concept: Yalin – only for total sediment
     - Parameters: slope, diameter, density, dw
     - Variables: transport_capacity
     - Boundary conditions: h_land, q_land

- Concept: Yalin particle differentiation – can be computed separately per sediment class
     - Parameters: density, diameter, wbcover, rivcell
     - Variables: transport_capacity
     - Boundary conditions: h_land, q_land

**Transport in overland flow**

- Concept: accuflux – can be computed per particle class separately
     - Parameters: rivercell
     - Variables: sediment flux
     - Boundary conditions: transport_capacity, eroded sediment, sediment reaching the river
 
### RiverSediment
The river sediment is mainly a mass balance in the river between the inputs (land, upstream), the river erosion and the deposition (here waterbodies are separated from river). The main mass balance should I guess stay in the general struct and some components like river erosion and deposition can move in separate structs.
Here there is some dependency in the calculations of erosion and deposition in the order of which calculations are made per particle class (deposition in priority of the larger particles and erosion in priority of the smaller particles) so that is why the mass balance may need to stay the general struct for now.
Note sure if a struct for waterbodies is needed?

**General**

- Parameters: nriv, riverslope, wbcover, wblocs, wbareas, trapping_efficiency, mean diameter river bed
- Variables: eroded sediment, deposited sediment, deposited sediment stored in the bed, sediment flux (total, suspended and bed loads)
- Boundary conditions: h_riv, q_riv, sediment from land erosion 

**TransportCapacity**
Note: all transport capacity equations are total no differentiation per particle class needed

- Concept: Bagnold
     - Parameters: cbagnold, ebagnold, width
     - Variables: transport_capacity
     - Boundary conditions: h_riv, q_riv
- Concept: EngelundandHansen
     - Parameters: mean diameter, river width, river slope, density
     - Variables : transport_capacity
     - Boundary conditions: h_riv, q_riv
- Concept: Yang – separate struct for sand and gravel equations? (note bug in the code)
     - Parameters: mean diameter, river slope, density
     - Variables: transport_capacity
     - Boundary conditions: h_riv, q_riv
     - Concept: Kodatie
     - Parameters: ak, bk, ck, dk, width, dt
     - Variables: transport_capacity
     - Boundary conditions: h_riv, q_riv
- Concept: Molinas
     - Parameters: mean diameter, width, density
     - Variables: transport_capacity
     - Boundary conditions: h_riv, q_riv

**River erosion**
River erosion is first previously eroded sediment and if not enough then erosion of the river bed and bank: one struct (combined o Knight only) or two structs? Some models like Delwaq do not allow to erode the river bed and bank but only the previously deposited material so maybe nice to separate?

- Concept: Knight – can be separated for each particle class (but lots of duplicate calculations then as separation is done at the very last equation)
     - Parameters: width, slope, kdband, kdbed, dt, dl, river_fraction
     - Variables: bed and bank erosion per particle class (seedbed, sedbank)
     - Boundary conditions: sediment_need, h_riv
- Concept: erosion of previously deposited sediment – can be separate but order matters
     - Parameters: 
     - Variables: eroded sediment and sediment leftover
     - Boundary conditions: sediment_need

**Settling**
Natural deposition with Einstein or settling of the particles to satisfy the transport capacity (where order matters) – separate deposition equation for waterbodies

- Concept: Einstein – can be separated for each particle class
     - Parameters: width, length, diameter
     - Variables: settling (per particle settclay)
     - Boundary conditions: q_riv, available sediment (from upstream+land+erosion)
- Concept: deposition of sediment excess compared to transport capacity – order matters (from gravel to clay)
     - Parameters: 
     - Variables: eroded sediment and sediment leftover
     - Boundary conditions: transport capacity exceedance, available sediment (from upstream+land+erosion)
- Concept: Camp for waterbodies - can be separated per particle
     - Parameters: wblocs, wbarea, wbtrap (large particles) diameter
     - Variables: deposition (per particle depclay)
     - Boundary conditions: q_riv, available sediment (from upstream+land+erosion)

**Separation between suspended and bed load**
Not sure if it needs its own struct. Here we decide suspension based on flow velocity while some models just assume it's always clay+silt(+small aggregates)

- Concept: Rouse – can be separated per particle
     - Parameters: slope, diameter
     - Variables: suspension/transport
     - Boundary conditions: sediment in transport, h_riv

### SedimentParticle
It would be good to create a SedimentParticle struct to at least store the sediment properties like diameter (different per class) or density (usually the same for each class). The questions is if that struct should then also contain the model variables and states such as soil erosion, sediment flux in the river etc or is only used to share parameters.

The different structs would be be: TotalSedimentParticle, ClayParticle, SiltParticle, SmallAggregateParticle, SandParticle, LargeAggregateParticle, GravelParticle

**SedimentParticle**:

- Parameters: soilfraction (fclay, fsilt etc), riverfraction (fclayriv etc), diameter (dmclay, dmsilt), density (rhos)
