### ISSUE TITLE
Formalize DoD requirements on Performance

### ISSUE THREAD

**Issue by CFBaptista** [Deltares/Wflow.jl#394]
Formalize the non-functional requirements on Performance for the version 1.0 release of wflow in the [DoD](https://github.com/Deltares/Wflow.jl/issues/393).

### Tasks
- [x] Propose non-functional requirements in DoD
- [x] Decide with team on functional and non-functional requirements to keep
- [x] Update description of functional and non-functional requirements in the DoD
- [x] Verify correct level of specificity with @deltamarnix 
- [x] Process review comments of @deltamarnix
